<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

?>
<?php
/** @var $block \Magento\Checkout\Block\Cart */
?>
<?php if (!$block->hasError()) :?>
    <?php $methods = $block->getMethods('methods') ?: $block->getMethods('top_methods') ?>
    <ul class="checkout methods items checkout-methods-items">
    	<li class="breakdown">
    		<span class="total-amount"></span>
    		<span class="breakdown-link">See Breakdown</span>
    	</li>
        <?php foreach ($methods as $method) :?>
            <?php $methodHtml = $block->getMethodHtml($method); ?>
            <?php if (trim($methodHtml) !== '') :?>
                <li class="item"><?= /* @noEscape */ $methodHtml ?></li>
            <?php endif; ?>
        <?php endforeach; ?>
    </ul>
<?php endif; ?>




<script type="text/javascript">
  require(['jquery', 'jquery/ui'], function($){
    $(document).ready( function() {
      $(".breakdown").click(function(){
      	if(window.innerWidth < 768){
      		$("div#cart-totals").addClass("highlight");
			setTimeout(function(){jQuery("div#cart-totals").removeClass("highlight");},1000);
		}
      });
    });
  });
</script>
